# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-app
#   namespace: default

# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hello-app
#   template:
#     metadata:
#       labels:
#         app: hello-app
#     spec:
#       containers:
#         - name: hello
#           image: public.ecr.aws/n7q7e9s6/argocd:639c89e0d4cbd1ab389b1613e0503bd7e43b8dc1
#           ports:
#             - containerPort: 5000
#           imagePullPolicy: Always
#           resources:
#             requests:
#               memory: "200Mi"
#               cpu: "250m"
#             limits:
#               memory: "250Mi"
#               cpu: "500m"



# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: hello-service
#   namespace: default
# spec:
#   selector:
#     app: hello-app
#   ports:
#     - port: 80
#       targetPort: 5000
#   # type: LoadBalancer
#   type: LoadBalancer

apiVersion: v1
kind: Pod
metadata:
  name: jar-pod
  labels:
    app: myapp

spec:
  containers:
    - name: jar-pod-container
      image: public.ecr.aws/n7q7e9s6/argocd:639c89e0d4cbd1ab389b1613e0503bd7e43b8dc1
      ports:
        - containerPort: 5000
          name: http-web-svc
      resources:
        limits:
          memory: 512Mi
          cpu: "0.5"
        requests:
          memory: 256Mi
          cpu: "0.2"

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instace
  name: jar-service

spec:
  selector:
    app: myapp

  ports:
    - port: 80
      targetPort: http-web-svc
      protocol: TCP
      nodePort: 30163

  # Types available in local are ClusterIP and NodePort
  type: LoadBalancer