name: Docker Image CI

on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v1
      with:     
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key:   ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
        aws-region: us-east-1        
        
    - uses: actions/checkout@v3
    - name: Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public   
    
    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: public.ecr.aws
        REGISTRY_ALIAS: n7q7e9s6
        REPOSITORY: argocd
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
        
